Repository AsyncRacing/AsyncRacing, pull requests merged in 2021-08, with the labels that each got.

#50 Fixing storybook config
  .storybook/main.js
  .storybook/preview.js
Labels: bug

#47 Start & Finish are draggable components
  src/components/Circuit/Circuit.tsx
  src/components/Circuit/Waypoint/Waypoint.tsx
  src/components/Course/ChallengeCourse.tsx
  src/components/GetMapTrack/GetMapTrack.tsx
  src/components/Map/ChallengeMap.tsx
Labels: enhancement

#52 Adding car-ride examples in ohio
  src/examples/nolan-car-ride-return01.gpx
  src/examples/nolan-car-ride-return02.gpx
  src/examples/nolan-car-ride-track01.gpx
  src/examples/nolan-car-ride-track02.gpx
  src/examples/nolan-walking-bear-malformed.gpx
Labels: enhancement

#49 Upload Multiple Tracks
  package.json
  src/components/GetMapTrack/GetMapTrack.tsx
  src/components/UploadButton/UploadButton.stories.tsx
  src/components/UploadButton/UploadButton.tsx
  src/components/UploadButton/useFileContent.ts
  src/model/parser.ts
  src/model/useFileToText.ts
  src/model/useFiles.ts
  src/model/useTextToPath.ts
Labels: enhancement

#51 Create trackTimer function
  package-lock.json
  package.json
  src/components/Timer/timer.test.ts
  src/components/Timer/timer.ts
  src/examples/Disney.gpx
  src/examples/default-challenge.ts
  src/examples/ian-motorcycle-ride-path.ts
  src/pages/Home/Home.css
Labels: enhancement

#57 Created Timer component
  src/components/GetMapTrack/GetMapTrack.tsx
  src/components/Timer/Timer.stories.tsx
  src/components/Timer/Timer.tsx
  src/components/Timer/getTime.ts
  src/components/Timer/timer.test.ts
Labels: enhancement

#71 Firebase improvements
  package-lock.json
  package.json
  public/_redirects
  src/components/CourseMap/CourseMap.stories.tsx
  src/components/CourseMap/CourseMap.tsx
  src/components/CourseSlider/CourseSlider.tsx
  src/components/Form/Form.tsx
  src/components/Timer/Timer.stories.tsx
  src/components/Timer/Timer.tsx
  src/components/Timer/getTime.ts
  src/components/Timer/timer.test.ts
  src/index.tsx
  src/model/firebase-config.ts
  src/model/useFiles.ts
  src/pages/Home/Home.css
  src/pages/Home/Home.tsx
  src/pages/Home/Title.css
  src/pages/Home/Title.tsx
  src/pages/IndexChallenges/IndexChallenges.tsx
  src/pages/NewChallenge/NewChallenge.stories.tsx
  src/pages/NewChallenge/NewChallenge.tsx
  src/pages/ShowChallenge/ShowChallenge.tsx
Labels: enhancement

#77 Updated Firebase config
  src/model/firebase-config.ts
Labels: bug

#76 Dont reload DB & Collect data in ShowChallenge page
  src/index.tsx
  src/pages/IndexChallenges/IndexChallenges.tsx
  src/pages/ShowChallenge/ShowChallenge.tsx
Labels: enhancement

#86 added logo to tab
  public/checkeredFlag.png
  public/index.html
  src/pages/IndexChallenges/IndexChallenges.tsx
Labels: enhancement

#87 Using Static Courses for immutable data
  src/components/CourseLines/CourseLinesMutable.tsx
  src/components/CourseLines/CourseLinesViewable.tsx
  src/components/CourseSlider/CourseSlider.tsx
  src/pages/NewChallenge/NewChallenge.tsx
  src/pages/ShowChallenge/ShowChallenge.tsx
Labels: enhancement, help wanted

#88 added steps to use asyncracing
  src/pages/IndexChallenges/GPXLink.css
  src/pages/IndexChallenges/GPXLink.tsx
  src/pages/IndexChallenges/IndexChallenges.tsx
Labels: enhancement

#89 added redirect to challenge
  src/components/ChallengeForm/ChallengeForm.tsx
Labels: bug, enhancement

#90 Awaiting async DB call
  src/components/ChallengeForm/ChallengeForm.tsx
Labels: bug

#91 Final Styling
  src/assets/flag-pin.png
  src/components/ChallengeForm/ChallengeForm.tsx
  src/components/CourseLines/CourseLinesMutable.tsx
  src/components/CourseLines/CourseLinesViewable.tsx
  src/components/Navbar/Navbar.tsx
  src/index.tsx
  src/pages/IndexChallenges/GPXLink.tsx
  src/pages/IndexChallenges/IndexChallenges.css
  src/pages/IndexChallenges/IndexChallenges.tsx
  src/pages/Instructions/Instructions.css
  src/pages/Instructions/Instructions.tsx
  src/pages/NewChallenge/NewChallenge.css
  src/pages/NewChallenge/NewChallenge.tsx
  src/pages/ShowChallenge/ShowChallenge.css
  src/pages/ShowChallenge/ShowChallenge.tsx
Labels: enhancement
